### ISSUE TITLE
This seems awesome, but...

### ISSUE THREAD

**Issue by wbhob** [reujab/bronze#2]
I'm running on ZSH on MacOS Sierra, and have no idea where to start with this. I don't really know how I can build a binary out of this source, since I don't work with go, and adding it to my path says `/Users/wilsonhobbs/.zshrc:16: command not found: bronze`. I would love some clarification and improved documentation!

**Comment by reujab** [comment]
Thanks for showing interest in this project!

1. The first thing you'll want to do if you want the custom icons, is install and enable a [Nerd Font](https://github.com/ryanoasis/nerd-fonts). If you don't want to install a patched font, you can [disable icons](https://github.com/reujab/bronze/wiki#bronze_icons).

2. Then you need to install the binary. Since you're running macOS, I'm unable to cross-compile for Darwin on Linux because of the [git2go](https://github.com/libgit2/git2go) dependency. (Once [go-git](https://github.com/src-d/go-git) provides support for stashes, I will use go-git, so I can provide pre-compiled binaries for macOS.)

3. Install [Go](https://golang.org/), add `$HOME/go/bin` to your `$PATH`, and run `go get github.com/reujab/bronze`. `bronze` should now be executable.

4. Add the following to your `~/.zshrc`:
```zsh
BRONZE=(status:black:white dir:blue:black git:green:black cmdtime:magenta:black)
export BRONZE_SHELL=zsh
eval "$(bronze init)"
```

You can read more about the available modules [here](https://github.com/reujab/bronze/wiki#modules).

I've never compiled this on macOS, so I'm not entirely sure it will compile. If it gives an error, please reply with the error message.

If it does compile on macOS, I will update the documentation accordingly.

**Comment by wbhob** [comment]
Ok the error I am getting is `bronze: unrecognized shell` with Zsh in iTerm 2

**Comment by wbhob** [comment]
Nevermind, I goofed (forgot to change to zsh), but now I get the error `precmd:1: bad math expression: operator expected at `N-15050598...'`

**Comment by reujab** [comment]
What is the output of `date +%s%3N`?

**Comment by wbhob** [comment]
15050599393N

**Comment by reujab** [comment]
The GNU `date` that comes with Linux is different that the BSD `date` that comes with macOS. The BSD `date` does not support nanoseconds/milliseconds in the output, and I cannot find any easy way to get the UNIX timestamp in milliseconds other than installing the GNU `date` on macOS.

1. Install [Homebrew](https://brew.sh/)
2. Install GNU binaries (`brew install coreutils`)
3. Add `alias date="gdate"` to your `.zshrc` before `bronze init`.

Or if you're not interested in the [`cmdtime`](https://github.com/reujab/bronze/wiki/Command-Time) module, you can skip this and remove `cmdtime:magenta:black` from `$BRONZE`.

**Comment by wbhob** [comment]
I did that and now get error `env: 0: No such file or directory`

**Comment by reujab** [comment]
And apparently BSD env differs from GNU env. This has been fixed. Update bronze using `go get -u github.com/reujab/bronze` and try again.

**Comment by wbhob** [comment]
Awesome, but now I'm getting _this_ error `fatal: No url found for submodule path 'vendor/libgit2/tests/resources/rebase-submodule/my-submodule' in .gitmodules
Failed to recurse into submodule path 'vendor/libgit2'
package gopkg.in/libgit2/git2go.v26: exit status 1`


I really really really appreciate your help with this! Sorry to bother you on the weekend!

**Comment by reujab** [comment]
That is an issue with git2go. See [libgit2/git2go#407](https://github.com/libgit2/git2go/issues/407). You can safely ignore this error.

Also, thank you for helping me make this app compatible with macOS.

**Comment by wbhob** [comment]
it's not letting me install the update because of the error, or I am still getting the same error

**Comment by reujab** [comment]
`go get -u github.com/reujab/bronze` downloaded the latest commit from GitHub, but didn't install it since git2go failed to compile for the second time. Running `go get github.com/reujab/bronze` after the previous command will install the latest version that was just downloaded. My bad.

**Comment by wbhob** [comment]
That worked, but now this 😢 
```
panic: strconv.Atoi: parsing "       0": invalid syntax

goroutine 19 [running]:
main.die(0x462bae0, 0xc42001a150)
	/Users/wilsonhobbs/go/src/github.com/reujab/bronze/main.go:25 +0x4a
main.statusSegment(0xc420073290)
	/Users/wilsonhobbs/go/src/github.com/reujab/bronze/status.go:31 +0x147
main.handleModule(0x7fff5fbff955, 0x6, 0xc420073290, 0xc420073260, 0x0, 0x0)
	/Users/wilsonhobbs/go/src/github.com/reujab/bronze/modules.go:12 +0x525
main.cmdPrintAction.func1(0xc420073260, 0x3, 0x3, 0xc420073290, 0xc42006f690)
	/Users/wilsonhobbs/go/src/github.com/reujab/bronze/print.go:46 +0x7f
created by main.cmdPrintAction
	/Users/wilsonhobbs/go/src/github.com/reujab/bronze/print.go:48 +0x20c
```

**Comment by reujab** [comment]
Wow, I didn't realize the BSD tools differed so much from the GNU tools.

Run the following:
```sh
go get -u github.com/reujab/bronze
go get github.com/reujab/bronze
```
You should see the same git2go error, you can ignore it.

**Comment by wbhob** [comment]
YES! IT WORKS! 

And it looks amazing, can't wait to dive in. Thanks so much for your help!

**Comment by reujab** [comment]
Thanks again for helping me make this compatible with macOS. If you have any other problems/requests, I'll be glad to help.
